# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_books_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='NoOfReader',
            field=models.IntegerField(null=True),
        ),
    ]
