# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170402_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Author',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
