# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20170402_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='WhoUpdated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
