# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_books_whoupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
